<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Long Nguyen, Marek Boulerice, Sarah Eshafi, Hui Tang">

<title>Creating Machine learning Model to Predict Presence of Coronary Artery Disease</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="heart_diagnostic_analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="heart_diagnostic_analysis_files/libs/quarto-html/quarto.js"></script>
<script src="heart_diagnostic_analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="heart_diagnostic_analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="heart_diagnostic_analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="heart_diagnostic_analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="heart_diagnostic_analysis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="heart_diagnostic_analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="heart_diagnostic_analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="heart_diagnostic_analysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">1. SUMMARY</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">2. INTRODUCTION</a></li>
  <li><a href="#data-validation-cleaning" id="toc-data-validation-cleaning" class="nav-link" data-scroll-target="#data-validation-cleaning">3. DATA VALIDATION &amp; CLEANING</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">4. METHOD</a>
  <ul class="collapse">
  <li><a href="#eda" id="toc-eda" class="nav-link" data-scroll-target="#eda">4.1 EDA</a></li>
  <li><a href="#ml-analysis" id="toc-ml-analysis" class="nav-link" data-scroll-target="#ml-analysis">4.2 ML-Analysis</a></li>
  </ul></li>
  <li><a href="#results-discussion" id="toc-results-discussion" class="nav-link" data-scroll-target="#results-discussion">5. RESULTS &amp; DISCUSSION</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">6. CONCLUSION</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">7. REFERENCES</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Creating Machine learning Model to Predict Presence of Coronary Artery Disease</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Long Nguyen, Marek Boulerice, Sarah Eshafi, Hui Tang </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">1. SUMMARY</h2>
<p>The following document covers a machine learning model analysis with a goal to predict angiographic coronary disease in patients. Data is pulled from patients undergoing angiography at the Cleveland Clinic in Ohio. This analysis is composed of Exploratory Data Analysis, testing of various machine models on a training data set, model optimization via hyperparameter, and final model performance analysis. The final model analysis shows that the model needs improvements before deployment for commercial use.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">2. INTRODUCTION</h2>
<p>Heart disease is the leading cause of death worldwide. Treating these heart diseases depends on capability of detecting symptoms and diagnosing cases earlier. One complication to diagnosing heart diseases is that many cases are found to be aymptomatic <span class="citation" data-cites="asymptomatic_coronary_disease">(<a href="#ref-asymptomatic_coronary_disease" role="doc-biblioref">Master 1969</a>)</span>. This creates an opportunity for application of machine learning methods, where the following question can be asked: Given various details about a clients medical status, can we create a statistical model to accurately predict whether the patient has the disease? The goal of the following analysis is to create a model that can anwswer this question. To be best suited to the problem, the model should retain a high accuracy while minimizing the number of false negatives (ie predicting that a patient does not have the heart disease when the patient in fact does).</p>
<p>In particular, this analysis focuses on detection of angiographic coronary disease. The data set used in creating our model was taken from 303 patients undergoing angiography Cleveland Clinic in Cleveland, Ohio <span class="citation" data-cites="heart_disease_45">(<a href="#ref-heart_disease_45" role="doc-biblioref">Janosi and Detrano 1989</a>)</span>. From this procedure, a set of parameters were collected about each patients, and a diagnosis of whether the patient had the angiographic coronary disease (signified by a diameter narrowing of the coronary artery by at least 50%). This is to serve as the target variable in our analysis</p>
<p>The set of parameters collected during the procedure, used as our features for model training, are as follows:</p>
<ul>
<li><strong>Age (in years)</strong> : Age of patient (years)</li>
<li><strong>Sex</strong> : Sex of patient (male or female)</li>
<li><strong>Chest pain type</strong>: categorical feature describing the type of pain experienced by the patient</li>
<li><strong>Resting Blood Pressure</strong>: numeric feature giving patients resting blood pressure</li>
<li><strong>Serum Cholesterol</strong> : numneric feature giving the patients Serum cholesterol in mg/dl</li>
<li><strong>Fasting blood sugar &gt; 120 mg/dl</strong> : binary feature indicating whether the patients Blood sugar level while fasting exceeded 120 mg/dl</li>
<li><strong>Resting electrocardiographic results</strong>: categorical feature reporting patients ECG results</li>
<li><strong>Maximum heart rate achieved</strong>: numeric feature giving maximum heart rate achieved by patent</li>
<li><strong>Exercise-induced angina</strong>: binary feature indicating whether patient underwent exercise induced angina</li>
<li><strong>ST depression induced by exercise relative to rest</strong>: numeric feature indicating the ST depression induced by exercise relative to rest</li>
<li><strong>Slope of the peak exercise ST segment</strong></li>
<li><strong>Thalassemia</strong> : categorical feature indicating if patient suffered from Thalassemia</li>
</ul>
<p>The following sections will discuss the decisions made and results in our Exploratory Data analysis, Machine learning model training, and final model performance</p>
<p>This report also drew information from the study done by <span class="citation" data-cites="OFlaherty2008">(<a href="#ref-OFlaherty2008" role="doc-biblioref">O’Flaherty et al. 2008</a>)</span> and <span class="citation" data-cites="thalassemia">(<a href="#ref-thalassemia" role="doc-biblioref">Athanasios Aessopos 2007</a>)</span></p>
</section>
<section id="data-validation-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="data-validation-cleaning">3. DATA VALIDATION &amp; CLEANING</h2>
<p>From an initial preview of the data, some issues were corrected immediately, before performing formal data validation. This includes removing invalid target values (i.e.&nbsp;values outside of range) and converting the values to their semantic meaning. The output of the data cleaning can be seen in <a href="#tbl-head" class="quarto-xref">Table&nbsp;1</a> below.</p>
<div class="cell" data-execution_count="2">
<div id="tbl-head" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-head-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Preview of cleaned data.
</figcaption>
<div aria-describedby="tbl-head-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="10">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 1%">
<col style="width: 3%">
<col style="width: 12%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 3%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Age (in years)</th>
<th style="text-align: left;">Sex</th>
<th style="text-align: left;">Chest pain type</th>
<th style="text-align: right;">Resting blood pressure (in mm Hg on admission to the hospital)</th>
<th style="text-align: right;">Serum cholesterol (in mg/dl)</th>
<th style="text-align: left;">Fasting blood sugar &gt; 120 mg/dl</th>
<th style="text-align: left;">Resting electrocardiographic results</th>
<th style="text-align: right;">Maximum heart rate achieved</th>
<th style="text-align: left;">Exercise-induced angina</th>
<th style="text-align: right;">ST depression induced by exercise relative to rest</th>
<th style="text-align: left;">Slope of the peak exercise ST segment</th>
<th style="text-align: right;">Number of major vessels (0–3) colored by fluoroscopy</th>
<th style="text-align: left;">Thalassemia</th>
<th style="text-align: left;">Diagnosis of heart disease</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">65</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">asymptomatic</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">177</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">normal</td>
<td style="text-align: right;">140</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: left;">upsloping</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">reversable defect</td>
<td style="text-align: left;">&lt; 50% diameter narrowing</td>
</tr>
<tr class="even">
<td style="text-align: right;">52</td>
<td style="text-align: left;">female</td>
<td style="text-align: left;">non-anginal pain</td>
<td style="text-align: right;">136</td>
<td style="text-align: right;">196</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">showing probable or definite left ventricular hypertrophy by Estes’ criteria</td>
<td style="text-align: right;">169</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: left;">flat</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">normal</td>
<td style="text-align: left;">&lt; 50% diameter narrowing</td>
</tr>
<tr class="odd">
<td style="text-align: right;">40</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">typical angina</td>
<td style="text-align: right;">140</td>
<td style="text-align: right;">199</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">normal</td>
<td style="text-align: right;">178</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: left;">upsloping</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">reversable defect</td>
<td style="text-align: left;">&lt; 50% diameter narrowing</td>
</tr>
<tr class="even">
<td style="text-align: right;">47</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">non-anginal pain</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">243</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">normal</td>
<td style="text-align: right;">152</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">upsloping</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">normal</td>
<td style="text-align: left;">&gt; 50% diameter narrowing</td>
</tr>
<tr class="odd">
<td style="text-align: right;">43</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">asymptomatic</td>
<td style="text-align: right;">115</td>
<td style="text-align: right;">303</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">normal</td>
<td style="text-align: right;">181</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: left;">flat</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">normal</td>
<td style="text-align: left;">&lt; 50% diameter narrowing</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Next, we evaluated whether the features in the train and test dataset are distributed similarly using deepchecks. The check concluded that that the features were not distributed significantly and our distributions are as expected.</p>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">4. METHOD</h2>
<p>The following section outlines the steps taken in manipulating our data and creating our model.</p>
<p>EDA is first conducted to obtain an idea of feature importance and to establish any important correlations to watch for. Machine learning analysis is then performed, where multiple models are tested and their performance compared. The best performing model is selected to proceed with. On this model, hyperparameter optimization is completed via random search to tune our model and obtain best results. Finally, the model is trained and tested on a separate data set, and evaluated for performance.</p>
<section id="eda" class="level3">
<h3 class="anchored" data-anchor-id="eda">4.1 EDA</h3>
<p>In this section, preliminary analysis is conducted to obtain an idea of possible correlations between features to be on the look out for. The results are presented below.</p>
<div id="fig-cat-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cat-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/categorical_distributions.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cat-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distributions of Categorical Features
</figcaption>
</figure>
</div>
<p>From <a href="#fig-cat-dist" class="quarto-xref">Figure&nbsp;1</a> above, we can see that there is class imbalance in the target (diagnosis of heart disease). This means we will need to consider balanced scoring metrics and models.</p>
<div id="fig-num-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-num-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/numeric_distributions.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-num-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Distributions of Numeric Features
</figcaption>
</figure>
</div>
<p><a href="#fig-num-dist" class="quarto-xref">Figure&nbsp;2</a> provides insights on some potential useful features for prediction. For example, it appears that patients testing negative for heart disease can achieve a higher maximum heart rate.</p>
<div id="fig-cor-mat" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cor-mat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/correlation_matrix.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cor-mat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Correlation Matrix
</figcaption>
</figure>
</div>
<p>Finally, in <a href="#fig-cor-mat" class="quarto-xref">Figure&nbsp;3</a>, we can see that there are correlations in some variables.</p>
</section>
<section id="ml-analysis" class="level3">
<h3 class="anchored" data-anchor-id="ml-analysis">4.2 ML-Analysis</h3>
<p>The following section outlines the procedure taken in creating our model and testing it on our data set. As this is a classification problem (predict whether the patient has the disease or not), the chosen models for testing in this analyis are a Logistic Regression model and a Suport Vector Classifier. These two models were selected as they have been shown to historically perform well on real world data sets.</p>
<p>Since this data set is somewhat imbalanced (~80/20 split on non-disease vs disease), the primary scoring metric to evaluate these models will be F1 score, though model accuracy is still taken into consideration. Due to the nature of the analysis, special attention is taken to minimize false negatives as they represent the most damaging type of error (predicting that a patient is free of the disease when he does in fact have it). To this effect, we look to maximize Recall.</p>
<p>The framework upon which this analysis is based has been adapted from DSCI573 Lab1.</p>
<section id="data-preprocessing" class="level4">
<h4 class="anchored" data-anchor-id="data-preprocessing">4.2.1. Data Preprocessing</h4>
<p>Features are sorted by type, and a column transformer object is created. On categorical columns, simple imputing is applied filling missing values with the most frequently occuring value. One hot encoding is then performed.</p>
<p>For numerical feature, standard scaling is applied to keep all features within the same range</p>
</section>
<section id="model-creation" class="level4">
<h4 class="anchored" data-anchor-id="model-creation">4.2.2. model creation</h4>
<p>Basic models (default hyperparameter values) are now generated. A dummy model is first created to use as a baseline to use for comparison. Then, a logistic regressor and support vector classifier model is created. 5-fold cross validation (CV) is performed on each model and scores are returned.</p>
<p>As discussed above, F1 score is to be the primary metric to evaluate model performance, with accuracy and recall as secondary metrics. This is reflected in the scoring metrics used in CV</p>
<p>Finally, a Confusion matrix was generated for each model to give an idea of false positive vs false negative rate.</p>
</section>
<section id="balanced-model-testing" class="level4">
<h4 class="anchored" data-anchor-id="balanced-model-testing">4.2.3. Balanced model testing</h4>
<p>Step 4.2.2 is repeated, this time creating balanced logistic regressor and SVC models, with all other hyperparameters held the same. Confusion matrices were once again generated to evaluate the types of errors seen. The goal of this step is to gain an understanding of how much accuracy is sacrificed at the benefit of improving F1 score.</p>
</section>
<section id="model-evaluation-and-selection" class="level4">
<h4 class="anchored" data-anchor-id="model-evaluation-and-selection">4.2.4. Model Evaluation and Selection</h4>
<p>With baseline models created, they are evaluated according to the criteria set above. CV scores of each model are presented below. First, standard deviation was evaluated to verify there are no abnormally performing models. Scores are presented in <a href="#tbl-model-cv-comps" class="quarto-xref">Table&nbsp;2</a> below.</p>
<p>Comparing the metrics across models, Balanced logistic regression yields the highest recall and second highest f1_score. For these reasons, we choose to proceed with <code>LogisticRegression(class_weight="balanced")</code>.</p>
<div class="cell" data-execution_count="3">
<div id="tbl-model-cv-comps" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-cv-comps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Comparison of cross-validation scores across model options.
</figcaption>
<div aria-describedby="tbl-model-cv-comps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="11">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 20%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">index</th>
<th style="text-align: right;">dummy</th>
<th style="text-align: right;">logreg</th>
<th style="text-align: right;">svc</th>
<th style="text-align: right;">logreg_bal</th>
<th style="text-align: right;">svc_bal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">fit_time</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: right;">0.007</td>
</tr>
<tr class="even">
<td style="text-align: left;">score_time</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.006</td>
</tr>
<tr class="odd">
<td style="text-align: left;">test_accuracy</td>
<td style="text-align: right;">0.746</td>
<td style="text-align: right;">0.781</td>
<td style="text-align: right;">0.787</td>
<td style="text-align: right;">0.751</td>
<td style="text-align: right;">0.766</td>
</tr>
<tr class="even">
<td style="text-align: left;">train_accuracy</td>
<td style="text-align: right;">0.746</td>
<td style="text-align: right;">0.838</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">0.813</td>
<td style="text-align: right;">0.929</td>
</tr>
<tr class="odd">
<td style="text-align: left;">test_precision</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.584</td>
<td style="text-align: right;">0.693</td>
<td style="text-align: right;">0.518</td>
<td style="text-align: right;">0.528</td>
</tr>
<tr class="even">
<td style="text-align: left;">train_precision</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.759</td>
<td style="text-align: right;">0.976</td>
<td style="text-align: right;">0.598</td>
<td style="text-align: right;">0.817</td>
</tr>
<tr class="odd">
<td style="text-align: left;">test_recall</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">0.76</td>
</tr>
<tr class="even">
<td style="text-align: left;">train_recall</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.525</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">0.815</td>
<td style="text-align: right;">0.93</td>
</tr>
<tr class="odd">
<td style="text-align: left;">test_f1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.477</td>
<td style="text-align: right;">0.362</td>
<td style="text-align: right;">0.598</td>
<td style="text-align: right;">0.619</td>
</tr>
<tr class="even">
<td style="text-align: left;">train_f1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">0.755</td>
<td style="text-align: right;">0.69</td>
<td style="text-align: right;">0.869</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="hyperparameter-optimization" class="level4">
<h4 class="anchored" data-anchor-id="hyperparameter-optimization">4.2.5. Hyperparameter optimization</h4>
<p>With our final model selected, hyperparameter tuning was done via a random search methodology to find the best value for our C hyperparameter, optimizing for F1 score. The cross-validation scores among the top three models are approximately equivalent. This suggests that the model’s performance is relatively stable across the parameter space, indicating that further tuning may not yield substantial improvements. With this C value selected, we proceed to evaluate the final model.</p>
</section>
<section id="final-model-scoring-and-evaluation" class="level4">
<h4 class="anchored" data-anchor-id="final-model-scoring-and-evaluation">4.2.6. Final model Scoring and Evaluation</h4>
<p>With hyperparameters selected the best model is fitted on the training set, then scored on both data sets. F1 score, Recall score and Accuracy are all computed across both data sets.</p>
<div id="fig-conf-mat" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-conf-mat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/confusion_matrix.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-conf-mat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Confusion Matrix on Test Data
</figcaption>
</figure>
</div>
<div class="cell" data-execution_count="4">
<div id="tbl-model-results" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Best model metrics.
</figcaption>
<div aria-describedby="tbl-model-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="12">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">Train</th>
<th style="text-align: right;">Test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">F1 Score</td>
<td style="text-align: right;">0.628</td>
<td style="text-align: right;">0.462</td>
</tr>
<tr class="even">
<td style="text-align: left;">Recall</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">0.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Accuracy</td>
<td style="text-align: right;">0.772</td>
<td style="text-align: right;">0.682</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
</section>
</section>
<section id="results-discussion" class="level2">
<h2 class="anchored" data-anchor-id="results-discussion">5. RESULTS &amp; DISCUSSION</h2>
<p>The model created needs further work and is not ready for deployment.</p>
<p>Our final test results yielded a F1 score of 0.462 and there is a large discrepancy to the training F1 score (0.628). This indicates that the model is overfitting. It is important to note that the test dataset is small with only 22 observations, which is likely contributing to the low F1 score.</p>
<p>Furthermore, our model has an accuracy of 68.2 percent. This value is worse than the baseline dummy accuracy, which again indicates that further work is required to improve the model.</p>
<p>With hyper parameter tuning the model achieved a higher F1 score compared to original model (0.628 on train F1 score compared to 0.598 F1 score for base model cv score).</p>
<p>To get more rigorous performance testing and confidence in our result in future iterations, there are several improvements we can make. It is recommended to seek further data, test more model types, and conduct feature engineering.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">6. CONCLUSION</h2>
<p>The model created showed some promise, being able to correctly classify presence of angiographic coronary disease with an accuracy of (68.2 percent).</p>
<p>However, the model performed poorly on F1 score and was not able to minimize the number of false negatives classified (recall of 0.6).</p>
<p>There are some limitations to this report that should be noted both at the analysis level and application level.</p>
<p>On the analysis side, only 2 models were tested. While their performance was encouraging, a more rigorous approach would test a variety of classifiers before proceeding with logistic regression.</p>
<p>As well, further hyperparameter optimization could be conducted. While a wide range of C-values were tested, Only 50 possible values were tested from this range. An improvement to this would be to randomly sample from a log-uniform distribution to obtain our best C value.</p>
<p>Lastly and perhaps most importantly, there is a large discrepancy between our test data set relative to the training data. The most reasonable explanation for this would be an test set too small to be representative.</p>
<p>On the application side, we should note that this model was tested specifically for one type of heart disease. The scope of the data used in training should be taken into account before proceeding with prediction on new data. As well this model requires a significant amount of medical information about a patient in order to create a prediction. Most of the information used to create the features to train the model is obtained through angiography, a process which itself ends in a diagnosis of the disease. So it is worth noting that even a high performing model will not be immediately applicable, though it gives confidence on the process.</p>
<p>Overall, we recommend further pursuing optimization of this model. Due to the high discrepancy between training and testing scores, we would strongly recommend performing further testing on the model on new, larger data sets before proceeding with it.</p>
</section>
<section id="references" class="level2 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">7. REFERENCES</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-thalassemia" class="csl-entry" role="listitem">
Athanasios Aessopos, Dimitrios Farmakis, Maria Kati. 2007. <span>“Heart Disease in Thalassemia Intermedia: A Review of the Underlying Pathophysiology.”</span> <a href="https://haematologica.org/article/view/4438">https://haematologica.org/article/view/4438</a>.
</div>
<div id="ref-heart_disease_45" class="csl-entry" role="listitem">
Janosi, Steinbrunn, Andras, and Robert Detrano. 1989. <span>“<span>Heart Disease</span>.”</span> UCI Machine Learning Repository.
</div>
<div id="ref-asymptomatic_coronary_disease" class="csl-entry" role="listitem">
Master, Arthur M. 1969. <span>“The Extent of Completely Asymptomatic Coronary Artery Disease.”</span> <a href="https://doi.org/10.1016/0002-9149(69)90064-2">https://doi.org/10.1016/0002-9149(69)90064-2</a>.
</div>
<div id="ref-OFlaherty2008" class="csl-entry" role="listitem">
O’Flaherty, M, E Ford, Steven Allender, P Scarborough, and S Capewell. 2008. <span>“<span class="nocase">Coronary heart disease trends in England and Wales from 1984 to 2004 : concealed levelling of mortality rates among young adults</span>,”</span> January. <a href="https://dro.deakin.edu.au/articles/journal_contribution/Coronary_heart_disease_trends_in_England_and_Wales_from_1984_to_2004_concealed_levelling_of_mortality_rates_among_young_adults/21047827">https://dro.deakin.edu.au/articles/journal_contribution/Coronary_heart_disease_trends_in_England_and_Wales_from_1984_to_2004_concealed_levelling_of_mortality_rates_among_young_adults/21047827</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>